/**
 * カタログの英語。**鍵は日本語の原文そのものです**（理由は `lang.ts`）。
 *
 * ここに無い原文は、日本語のまま画面に出ます。壊れて見えない代わりに
 * **日本語話者は訳し漏れに気づけない**ので、
 * `scripts/check-catalog-lang.mjs` が機械で数えます。
 *
 * 差し込みのある文言は `{0}` を使い、呼ぶ側で `.replace("{0}", …)` します。
 * 語順が言語で変わるので、差し込みの位置ごと訳せる形にしています。
 */
export const EN: Record<string, string> = {
  "/* theme.css が既定で入れているもの */\nbody { overflow-wrap: break-word; }\nimg, video, svg, iframe { max-width: 100%; }\npre { overflow-x: auto; }\n.wt-gap > * { min-width: 0; }": "/* What theme.css puts in by default */\nbody { overflow-wrap: break-word; }\nimg, video, svg, iframe { max-width: 100%; }\npre { overflow-x: auto; }\n.wt-gap > * { min-width: 0; }",
  "// ボタンから出すなら、これだけです。await も if も要りません。\n<ActionButton\n  variant=\"danger\"\n  confirm={{\n    title: \"この記事を削除しますか？\",\n    description: \"元に戻せません。\",\n    confirmLabel: \"削除する\",\n    tone: \"danger\",\n  }}\n  action={() => api.remove(id)}\n>\n  削除する\n</ActionButton>\n\n// ボタン以外（メニューの項目など）から出したいときだけ、直接呼びます\nconst confirm = useConfirm();\nif (!(await confirm(\"下書きを破棄しますか？\"))) return;": "// From a button, this is all of it. No await, no if.\n<ActionButton\n  variant=\"danger\"\n  confirm={{\n    title: \"Delete this article?\",\n    description: \"This cannot be undone.\",\n    confirmLabel: \"Delete\",\n    tone: \"danger\",\n  }}\n  action={() => api.remove(id)}\n>\n  Delete\n</ActionButton>\n\n// Call it directly only when the trigger is not a button (a menu item, say)\nconst confirm = useConfirm();\nif (!(await confirm(\"Discard this draft?\"))) return;",
  "// 命令 → role=\"menu\" / \"menuitem\"\n<DropdownMenu label=\"操作\" items={[{ label: \"複製\", onSelect: dup }]} />\n\n// リンク → ただの <ul><li><a>\n<NavDropdown label=\"製品\" items={[{ label: \"料金\", href: \"/pricing\" }]} />": "// Commands → role=\"menu\" / \"menuitem\"\n<DropdownMenu label=\"Actions\" items={[{ label: \"Duplicate\", onSelect: dup }]} />\n\n// Links → a plain <ul><li><a>\n<NavDropdown label=\"Products\" items={[{ label: \"Pricing\", href: \"/pricing\" }]} />",
  "1 行の長さ": "Line length",
  "1024px 未満で縦積み": "Stacks below 1024px",
  "16px 未満だと iOS が自動拡大します": "Below 16px, iOS zooms the page automatically",
  "2 列": "2 columns",
  "2 回失敗 → 自動で 3 回目": "Fails twice, then retries a third time automatically",
  "2 段目": "Second row",
  "24px 未満は指で押しづらい": "Under 24px is hard to hit with a finger",
  "3 件の変更を反映しました": "3 changes applied",
  "320px で 8 列の表は、横スクロールできても実用に耐えません。\r\n          なので": "An eight-column table at 320px is unusable even with horizontal scroll. So",
  "6 列": "6 columns",
  "6 秒かかる処理です。実行中に「中断」を押すとリクエストが止まり、状態が idle に戻ります。ctx.signal を fetch に渡すだけで実現できます。": "This takes six seconds. Press Abort while it runs and the request stops, with the state back at idle. All it takes is passing ctx.signal to fetch.",
  "768px 未満で縦積み": "Stacks below 768px",
  "8 文字以上": "8 characters or more",
  "8 日以内なら可能です。": "Within 8 days, yes.",
  "<ActionButton action={() => api.save(form)}>\n  保存する\n</ActionButton>": "<ActionButton action={() => api.save(form)}>\n  Save\n</ActionButton>",
  "<AsyncForm action={api.signup} submitLabel=\"アカウントを作成\">\n  <Field name=\"email\" label=\"メールアドレス\" type=\"email\" required />\n</AsyncForm>": "<AsyncForm action={api.signup} submitLabel=\"Create account\">\n  <Field name=\"email\" label=\"Email\" type=\"email\" required />\n</AsyncForm>",
  "<AsyncSelect\n  label=\"担当者\"\n  name=\"ownerId\"\n  loader={(q, ctx) => jsonRequest<User[]>(`/api/users?q=${q}`, { ctx })}\n  getKey={(u) => u.id}\n  getLabel={(u) => u.name}\n  getFormValue={(u) => `user_${u.id}`}\n  onChange={setOwner}\n/>": "<AsyncSelect\n  label=\"Assignee\"\n  name=\"ownerId\"\n  loader={(q, ctx) => jsonRequest<User[]>(`/api/users?q=${q}`, { ctx })}\n  getKey={(u) => u.id}\n  getLabel={(u) => u.name}\n  getFormValue={(u) => `user_${u.id}`}\n  onChange={setOwner}\n/>",
  "<DataTable\n  rows={rows}\n  columns={columns}\n  getKey={(r) => r.id}     // selectable のときは必須\n  selectable\n  selectionActions={(keys, clear) => (\n    <Button size=\"sm\" onClick={() => bulkDelete(keys)}>削除</Button>\n  )}\n/>": "<DataTable\n  rows={rows}\n  columns={columns}\n  getKey={(r) => r.id}     // required when selectable\n  selectable\n  selectionActions={(keys, clear) => (\n    <Button size=\"sm\" onClick={() => bulkDelete(keys)}>Delete</Button>\n  )}\n/>",
  "<DataTable rows={rows} columns={columns} pageSize={5} />\n\n// 列定義。label はカード表示で唯一の手がかりになるので必須\n{ key: \"amount\", label: \"金額\", sortable: true, align: \"end\",\n  get: (r) => `¥${r.amount.toLocaleString(\"ja-JP\")}` }": "<DataTable rows={rows} columns={columns} pageSize={5} />\n\n// Column definition. label is required — in card view it is the only clue left\n{ key: \"amount\", label: \"Amount\", sortable: true, align: \"end\",\n  get: (r) => `$${r.amount.toLocaleString(\"en-US\")}` }",
  "<Dialog open={open} onOpenChange={setOpen} title=\"設定\">\n  中身\n</Dialog>\n\n// 端から出すシート（狭い画面のメニューなどに）\n<Dialog placement=\"sheet-right\" ... />": "<Dialog open={open} onOpenChange={setOpen} title=\"Settings\">\n  Content\n</Dialog>\n\n// A sheet that slides in from the edge (for narrow-screen menus)\n<Dialog placement=\"sheet-right\" ... />",
  "<Disclosure summary=\"送料について\">3,000 円以上で無料です。</Disclosure>\n\n<Accordion items={[{ summary: \"…\", content: \"…\" }]} />": "<Disclosure summary=\"About shipping\">Free over $30.</Disclosure>\n\n<Accordion items={[{ summary: \"…\", content: \"…\" }]} />",
  "<Frame ratio=\"16/9\">\n  <Img src=\"/hero.avif\" alt=\"\" priority />   {/* 最初の画面に入る画像 */}\n</Frame>": "<Frame ratio=\"16/9\">\n  <Img src=\"/hero.avif\" alt=\"\" priority />   {/* an image in the first screenful */}\n</Frame>",
  "<Scrollable label=\"売上の表\">\n  <table>…</table>\n</Scrollable>\n\n// スクロールバーが邪魔なとき（端の影は残ります）\n<Scrollable label=\"売上の表\" scrollbar=\"hidden\">…</Scrollable>": "<Scrollable label=\"Sales table\">\n  <table>…</table>\n</Scrollable>\n\n// When the scrollbar is in the way (the edge shadow stays)\n<Scrollable label=\"Sales table\" scrollbar=\"hidden\">…</Scrollable>",
  "<SiteFooter\n  brand=\"Example Studio\"\n  groups={[{ label: \"サイト\", items: [{ href: \"/blog\", label: \"ブログ\" }] }]}\n  note=\"© 2026 Example Studio\"\n/>": "<SiteFooter\n  brand=\"Example Studio\"\n  groups={[{ label: \"Site\", items: [{ href: \"/blog\", label: \"Blog\" }] }]}\n  note=\"© 2026 Example Studio\"\n/>",
  "<SkipLink />\n<SiteHeader\n  brand=\"Example Studio\"\n  items={[{ href: \"/works\", label: \"Works\" }]}\n  currentPath={Astro.url.pathname}   // ルーターに依存しない\n  actions={<ThemeSwitcher />}\n/>": "<SkipLink />\n<SiteHeader\n  brand=\"Example Studio\"\n  items={[{ href: \"/works\", label: \"Works\" }]}\n  currentPath={Astro.url.pathname}   // no router dependency\n  actions={<ThemeSwitcher />}\n/>",
  "<Tabs items={items} value={tab} onValueChange={setTab}>\n  <TabPanel value=\"a\">…</TabPanel>\n</Tabs>\n\n// 切り替えが重いときは manual（Enter を押すまで切り替えない）\n<Tabs activation=\"manual\" ... />": "<Tabs items={items} value={tab} onValueChange={setTab}>\n  <TabPanel value=\"a\">…</TabPanel>\n</Tabs>\n\n// Use manual when switching is expensive (nothing changes until Enter)\n<Tabs activation=\"manual\" ... />",
  "<Tiles columns={{ mobile: 2, tablet: 3, desktop: 4 }} space=\"md\" />\n\n// 列数を決めない書き方\n<Tiles columns=\"repeat(auto-fill, minmax(9rem, 1fr))\" space=\"md\" />": "<Tiles columns={{ mobile: 2, tablet: 3, desktop: 4 }} space=\"md\" />\n\n// Or leave the column count undecided\n<Tiles columns=\"repeat(auto-fill, minmax(9rem, 1fr))\" space=\"md\" />",
  "ActionProvider — 書き忘れの受け皿": "ActionProvider — a net for what you forgot",
  "Astro に置くとき": "Placing it in Astro",
  "Columns / Column — 段組": "Columns / Column — column layout",
  "ContentBlock は本文の幅を制限します。prose は em 単位なので、\r\n                  文字を小さくすると幅も自動的に狭まり、1 行の字数が保たれます。": "ContentBlock caps the width of body text. prose is in em, so smaller text automatically gets a narrower measure and the characters per line stay constant.",
  "Ctrl+F のページ内検索が閉じた中身も見つけてくれるのも、\r\n          自前で作ると失うものです。1 つだけ開く動きは": "Ctrl+F finding text inside a closed section is another thing you lose by hand-rolling it. Opening only one at a time is",
  "Frame で包む（動きません）": "Wrapped in Frame (nothing shifts)",
  "Inline — 横に並べて折り返す": "Inline — lay out horizontally and wrap",
  "JavaScript が 1 行も要りません。": "Not one line of JavaScript.",
  "JavaScript を切っても開閉します。": "It still opens and closes with JavaScript disabled.",
  "Lighthouse のスコアを 95 以上にする": "Get the Lighthouse score above 95",
  "Markdown を流し込む場所の見た目です。": "How a block of Markdown is styled.",
  "OGP 画像の生成を自動化": "Automate OGP image generation",
  "Scrollable — 潰さず、はみ出させず": "Scrollable — neither squashed nor overflowing",
  "Stack — 縦に積む": "Stack — stack vertically",
  "Tiles — 等間隔グリッド": "Tiles — an even grid",
  "action が呼ばれた回数:": "Times the action was called:",
  "callback がわざと失敗します": "The callback fails on purpose",
  "callback が投げる": "Callback throws",
  "const answer = 42;\n// 横に長いコードは折り返さず、この中だけ横スクロールします": "const answer = 42;\n// Wide code does not wrap; it scrolls horizontally inside this box",
  "const next = useInteractionGuard();\n\nfunction goNext() {\n  if (!next.tryLock()) return;\n  router.push(\"/checkout\");\n}\n\n<Button onClick={goNext} disabled={next.isLocked}>\n  次へ\n</Button>\n\n// 同じ画面でやり直せるようになった時だけ\nnext.release();": "const next = useInteractionGuard();\n\nfunction goNext() {\n  if (!next.tryLock()) return;\n  router.push(\"/checkout\");\n}\n\n<Button onClick={goNext} disabled={next.isLocked}>\n  Continue\n</Button>\n\n// Only when the same screen is ready to try again\nnext.release();",
  "const state = useAction(api.remove, {\n  // ctx.signal を渡せば、guard の中の通信も一緒に止まります\n  guard: async (input, ctx) => confirmSomething(input, ctx),\n});\n\nstate.abort();   // guard を待っている間でも効きます": "const state = useAction(api.remove, {\n  // Pass ctx.signal along and requests inside the guard stop too\n  guard: async (input, ctx) => confirmSomething(input, ctx),\n});\n\nstate.abort();   // works even while the guard is still running",
  "dividers（線は実際の要素なので、上下の余白が揃います。上のボタンで変わります）": "dividers (the rule is a real element, so the space above and below matches. The buttons above change it)",
  "fetch はアップロードの進捗を取れません。": "fetch cannot report upload progress.",
  "guard が遅い": "Slow guard",
  "guard を待っている間の中断": "Aborting while the guard is still running",
  "npm run check          # 見に行く URL は package.json に書いてあります\n                       # （astro なら 4321、vite なら 4173）\n\n端末幅チェック: 1 ページ × 5 幅\n\n  ✗ http://localhost:4321  @ 320 (小さいスマホ)\n      横に 577px はみ出しています\n        ↳ <p class=\"…\"> が 577px 外へ  \"https://example.com/very/long…\"\n        → 長い文字列なら overflow-wrap、表やコードなら <Scrollable> で囲んでください\n      入力欄の文字が 16px 未満: 3 件 (name=14px, email=14px, password=14px)\n        → iOS では触れた瞬間に画面が自動拡大されます\n      タップ領域が 24px 未満: 2 件 (a 43x20 \"Works\", a 54x20 \"Contact\")\n        → 指で押しづらく、WCAG 2.1 AA の最低基準を下回ります": "npm run check          # the URL it visits is in package.json\n                       # (4321 for astro, 4173 for vite)\n\nScreen width check: 1 page x 5 widths\n\n  ✗ http://localhost:4321  @ 320 (small phone)\n      577px of horizontal overflow\n        ↳ <p class=\"…\"> extends 577px past the edge  \"https://example.com/very/long…\"\n        → wrap long strings with overflow-wrap; wrap tables and code in <Scrollable>\n      inputs under 16px: 3 (name=14px, email=14px, password=14px)\n        → iOS zooms the page the moment these are focused\n      tap targets under 24px: 2 (a 43x20 \"Works\", a 54x20 \"Contact\")\n        → hard to hit, and below the WCAG 2.1 AA minimum",
  "onError を書かずに失敗させる": "Fail without an onError",
  "onError を自分で書く": "Write your own onError",
  "tablet（既定）": "tablet (default)",
  "width=&quot;18rem&quot;（段階外）": "width=&quot;18rem&quot; (off-scale)",
  "width=&quot;auto&quot;（残りを埋める）": "width=&quot;auto&quot; (fills the rest)",
  "wrap（既定）— 入り切らなければ折り返す": "wrap (default) — wraps when it does not fit",
  "{0} 件を処理しました": "Processed {0} items",
  "— いまは": "— currently",
  "— 折り返さず、入り切らなければ横スクロール": "— no wrapping; scrolls horizontally when it does not fit",
  "——\r\n          それでも止まります。下の数字が増えなければ止まっています。": "— and it still stops. If the number below does not go up, it stopped.",
  "← → で移動、Home / End で端へ。無効なタブは飛ばします。": "Arrow keys move, Home / End jump to the ends. Disabled tabs are skipped.",
  "↑ 12 個あるので横スクロールします（manual: 矢印で動かしても切り替わりません）": "↑ Twelve of them, so it scrolls horizontally (manual: arrows move focus without switching)",
  "↑ こちらは 1 つ開くと他が閉じます（JS ではなく HTML の機能です）": "↑ Opening one closes the others here — that is HTML, not JS",
  "。\r\n            色だけで示すと、色を見分けにくい人に届かないためです。": ". Signalling with color alone does not reach people who cannot tell the colors apart.",
  "「{0}」の削除に失敗しました": "Could not delete “{0}”",
  "「{0}」の更新に失敗しました": "Could not update “{0}”",
  "「{0}」の追加に失敗しました": "Could not add “{0}”",
  "「たぶん大丈夫」ではなく、実際のブラウザを 5 つの幅で開いて機械的に調べます。崩れがあると終了コード 1 を返すので、CI にそのまま載せられます。": "Not \"it is probably fine\" — a real browser is opened at five widths and measured. It exits 1 when something is broken, so it drops straight into CI.",
  "あり": "on",
  "いちばん使う部品です。子側に margin を書く必要はありません。": "The one you will use most. The children never need a margin of their own.",
  "お名前": "Name",
  "お名前を入力してください": "Please enter your name",
  "が付いています。": "is applied.",
  "が必須なのはそのためです。ウィンドウを狭めると切り替わります。": "is required for that reason. Narrow the window to see it switch.",
  "が決めています。\r\n            和文はおよそ 40 字で折り返すので、視線が戻る距離が短く保たれます。\r\n            長い URL（": "decides it. Japanese wraps at roughly 40 characters, which keeps the distance your eye travels back short. A long URL (",
  "が隠すので利用者が XHR を書くことはありません。\r\n          1 ファイルずつ送るので、失敗した分だけ再送できます。": "hides it, so you never write XHR yourself. Files go one at a time, so you can resend only what failed.",
  "が非同期のとき、待っている間に中断したり画面を離れたりできます。": "is async, you can abort or leave the page while it is still running.",
  "ここには来られません。": "You cannot get here.",
  "ここは説明文です。読み上げにも渡されます。": "This is the description. Screen readers get it too.",
  "こちらは先に場所が取ってあるので、位置が変わりません。": "This one reserves its space first, so nothing moves.",
  "このカタログ上部のタブも、これに差し替えました。": "The tabs at the top of this catalog were switched to it as well.",
  "このカタログ自身のヘッダを": "this catalog's own header",
  "このカタログ自身を、指定した幅で表示します。iframe は独立した\r\n          ビューポートなので、": "This shows the catalog itself at a chosen width. An iframe is its own viewport, so",
  "このデモの偽サーバーは、名前に": "The fake server in this demo rejects only names containing",
  "このデモの偽サーバーは、題名に fail を含むものだけ拒否します。": "The fake server in this demo rejects only titles containing “fail”.",
  "このドメインは登録できません": "That domain cannot be registered",
  "このヘッダは": "This header is",
  "この文章の位置が、画像の到着で下へ動きます。": "This paragraph gets pushed down when the image arrives.",
  "この章はまだ準備中です": "This section is not ready yet",
  "この裏側は押せません。Tab を何度押してもここから出ません。": "Nothing behind this is clickable. Press Tab as often as you like — focus stays here.",
  "この記事を削除しますか？": "Delete this article?",
  "これは通知されない": "This one is not notified",
  "されます\r\n          （検索語を": "(the search term is",
  "するので、\r\n          ページを移っても並べ替えても残ります。\r\n          ヘッダのチェックは「いま表示している行」だけが対象です。\r\n          他のページの分を含めた合計を「N 件選択中」に出します。\r\n          Shift+クリックで範囲選択、チェックのクリックは行クリックに伝播しません。": ", so it survives paging and sorting. The header checkbox covers only the rows currently shown, while the total including other pages appears as \"N selected\". Shift+click selects a range, and clicking a checkbox does not propagate to the row.",
  "そのあと action が始まってはいけません。": "The action must not start afterwards.",
  "その下の本文がガクッと下へずれます": "the text below jumps downward",
  "その操作だけ": "just that one operation",
  "たくさんある例": "With many of them",
  "ただし守りではありません。": "It is not a defense, though.",
  "ただし背面のスクロールだけは止まらない": "except the background still scrolls",
  "で、\r\n          Tab キーで止まるのは選択中の 1 つだけです（roving tabindex）。\r\n          入りきらないときは潰さずに横スクロールします。": ", and Tab stops on only the selected one (roving tabindex). When they do not fit, they scroll horizontally instead of being squashed.",
  "できました": "Done",
  "です。": ".",
  "です。ページの一部として埋め込むときは、": ". When embedding it as part of a page,",
  "で変えられます。": "changes it.",
  "で読み上げが変わるためです。": "changes how it is announced.",
  "と": "and",
  "どちらでも、はみ出さず、列が縦に割れません": "Neither overflows, and no column splits vertically",
  "なし": "off",
  "にしているのはそのためです。": "is why it is set that way.",
  "に入れたエラーは、\r\n          対応する入力欄の下へ自動で表示され、打ち直すと消えます。\r\n          メールを空欄にするか": "appear under the matching input on their own and clear as you retype. Leave the email empty, or",
  "に組み替え、\r\n          各値に列名を付けます。列定義の": ", attaching the column name to every value. In the column definition,",
  "に落ちるので、置かなくても壊れません。": ", so nothing breaks without it.",
  "に関数を渡すだけ。\r\n          押している間の無効化、連打の防止、成功の表示、失敗時のメッセージ、\r\n          自動リトライが最初から入っています。": ". Disabling while it runs, the double-click guard, the success state, the failure message, and automatic retry are all in from the start.",
  "の": "of",
  "ので、そこだけ自分で止めています。開閉で画面が横に揺れないよう、\r\n          スクロールバーの幅は常に確保してあります。": ", so that one part is stopped by hand. The scrollbar width is always reserved so the page does not jump sideways as it opens and closes.",
  "のように段階に無い値もそのまま書けます（Tailwind の": "Off-scale values work as written, too — the same relationship Tailwind has between",
  "の依存キーにしているため）。古い応答が新しい応答を上書きする競合は、\r\n          この層で既に解けています。↑↓ Enter Esc Home End で操作できます。": "). The race where a stale response overwrites a newer one is already solved at this layer. Arrow keys, Enter, Esc, Home, and End all work.",
  "の切り替わりもそのまま起きます。": "switches exactly as it would.",
  "の担当で、両方が幅を決めると同じ基準が 2 か所に増えて必ずずれるためです。\r\n          この部分だけ「部品は外側の余白を持たない」の原則を破っています。": "owns it — if both decided the width, the same rule would live in two places and drift. This is the one spot that breaks the \"components own no outer spacing\" principle.",
  "の指定は効きません（1/3 のまま縦に並べても読みにくいだけなので、\r\n          全幅にします）。いつ畳むかは": "has no effect (a 1/3 column stacked vertically is just hard to read, so it goes full width). When it folds is set by",
  "の間に": "between",
  "の関係と同じです）。\r\n          段階ごとの実寸はテーマで変わるので、上のスイッチを切り替えると幅も変わります。": ". The actual size of each step changes with the theme, so flipping the switch above changes the widths too.",
  "は": "is",
  "はみ出している要素まで名指しで出します": "names the element that overflows",
  "はアプリの命令用で、リンクの集まりに付けると「リンクだと分からなくなる」\r\n          という壊れ方をします。": "is for application commands. Put it on a set of links and it breaks in a specific way: they stop being recognizable as links.",
  "は挟めないからです。": "cannot be placed in between.",
  "まだ中身がありません。他のタブをご覧ください。": "Nothing here yet. Try one of the other tabs.",
  "まとめて処理": "Process together",
  "もう 1 つ": "One more",
  "もう一度許可する": "Allow again",
  "や": "or",
  "やることの題名": "Task title",
  "やることを追加": "Add a task",
  "をそのまま中に入れられます。": "goes straight inside.",
  "を付けなくても開閉します。読み込みの遅い回線で「押しても何も起きない数秒」が\r\n          生まれないのが理由です。Esc で閉じる処理だけ JS\r\n          で足していますが、無くてももう一度押せば閉じます。": "opens and closes without it. The reason is that on a slow connection there is never a stretch of seconds where pressing does nothing. Only closing on Esc is added in JS, and without that you can just press again.",
  "を付けると消えます。": "removes it.",
  "を使うので、フォーカスの閉じ込め・背面の無効化・Esc・最前面表示は\r\n          ブラウザ任せです。": ", so the focus trap, disabling what is behind, Esc, and staying on top are all the browser's job.",
  "を使っています。\r\n          フォーカスの閉じ込め・背景の暗転・Esc で閉じる・最前面表示・\r\n          閉じたあとのフォーカス復帰が、全部ブラウザ任せになります。\r\n          Provider が無いときは": ". The focus trap, the dimmed backdrop, closing on Esc, staying on top, and restoring focus afterwards all become the browser's job. Without the Provider it falls back to",
  "を入れると、\r\n          失敗したときの表示を確認できます。": "and you can watch what a failure looks like.",
  "を含むファイルだけ拒否します。": "Only files whose name contains that are rejected.",
  "を書いた場合はそちらが優先され、通知は出ません。": "takes precedence when you write one, and no notification appears.",
  "を書かなかったアクションが失敗すると、\r\n          画面隅に通知が出ます。エラー処理の書き忘れが握り潰されなくなります。\r\n          個別に": "fails without one, a notification appears in the corner. A forgotten error handler stops swallowing the failure. An individual",
  "を見ます\r\n          （縦を横に回すと、ページを縦に読んでいる途中で止まります）。": "is used (turning vertical movement into horizontal would stop the page while you are reading down it).",
  "アカウントを作成": "Create account",
  "アクセシビリティ": "Accessibility",
  "カタログの章": "Catalog sections",
  "カード": "Card",
  "カードと銀行振込です。": "Card and bank transfer.",
  "キーで保持": "Kept by key",
  "ゲーム": "Games",
  "コミュニティ": "Community",
  "コード例": "Example code",
  "サポート": "Support",
  "サーバーが受け取りを拒否しました": "The server refused it",
  "サーバーが混み合っています。少し待って再実行してください。": "The server is busy. Wait a moment and run it again.",
  "シート": "Sheet",
  "ストリームで測れるのは「ブラウザがデータを引き取った時点」で、\r\n          送信完了ではないためです。なので内部では XHR を使いますが、": "What a request stream measures is the moment the browser pulled the data, not the moment it finished sending. So internally it uses XHR, but",
  "スマホでは元の幅がもともと狭いので、どの幅を選んでもほとんど変わりません。": "On a phone the starting width is already narrow, so the choice barely changes anything.",
  "スマホ表示が壊れる原因のほとんどは「縮まない中身」です。折り返せない文字列と、実寸の大きい画像。どちらもテンプレート側で受け止めるので、利用者が overflow-wrap を知らなくても崩れません。ウィンドウを狭めても横スクロールは出ません。": "Almost every broken mobile layout comes from content that will not shrink: unbreakable strings and oversized images. The template absorbs both, so nothing breaks even if you have never heard of overflow-wrap. Narrow the window and no horizontal scrollbar appears.",
  "タグ（複数）": "Tags (multiple)",
  "タスク": "Tasks",
  "タップ領域": "Tap target",
  "タブ {0}": "Tab {0}",
  "タブレット幅未満では 1 行 = 1 カード": "Below tablet width, one row becomes one card",
  "タブレット横": "Tablet landscape",
  "タブレット縦": "Tablet portrait",
  "チーム": "Team",
  "デザイン": "Design",
  "データあり": "With data",
  "ドキュメント": "Docs",
  "ナビ/開閉": "Nav & disclosure",
  "パスワード": "Password",
  "パスワードは 8 文字以上にしてください": "Use at least 8 characters",
  "ヒーローセクションの文言を確定する": "Finalize the hero section copy",
  "フォームを繋ぐ": "Wire up a form",
  "フォーラム": "Forum",
  "ブラウザ標準の": "The browser's own",
  "ブラウザ標準の日付入力です": "The browser's own date input",
  "プライバシー": "Privacy",
  "プラン": "Plan",
  "プランを選んでください": "Please choose a plan",
  "プロダクト": "Product",
  "ヘッダの下の中身。「料金」に": "The content under the header. “Pricing” has",
  "ページ全体の骨格。最大幅・左右の余白・上下のリズムをこれらが持ちます。": "The frame of the whole page. Max width, side padding, and vertical rhythm live here.",
  "マイページから出せます。": "You can do it from your account page.",
  "メールアドレス": "Email",
  "メールアドレスの形式が正しくありません": "That does not look like an email address",
  "リンクの": "for links,",
  "レイアウト": "Layout",
  "レイアウトを直す": "Fix the layout",
  "ロゴ": "Logo",
  "一時的な通信エラー": "A temporary network error",
  "一覧の取得に失敗しました": "Could not load the list",
  "下に送信された値を出しました": "The submitted values are shown below",
  "下は実物です（sticky は切ってあります）。画面を狭くするとハンバーガーに変わります。": "Below is the real thing (sticky is turned off). Narrow the window and it becomes a hamburger.",
  "下書きを破棄しますか？": "Discard this draft?",
  "下線は消していません": "The underline is left in place",
  "両方開けます。": "Both can be open.",
  "中": "Medium",
  "中央に出す": "Center",
  "中断": "Abort",
  "中断とスケルトン": "Abort and skeleton",
  "中断を自分では見ていません": "does not check for the abort itself",
  "中身です。矢印は開くと 180 度回ります。": "The content. The arrow rotates 180 degrees when open.",
  "件名": "Subject",
  "件数": "Count",
  "任意の余白": "Any spacing value",
  "会社情報": "Company",
  "会社概要": "About",
  "低": "Low",
  "何か入力して、別のタブへ行って戻ってみてください": "Type something, switch to another tab, and come back",
  "余白の既定は 9 段階": "Nine spacing steps by default",
  "余白は 9 段階が既定なので配置で迷いません。ただし 9 段階は制限ではなく、\r\n            段階に無い値もそのまま書けます。\r\n            非同期処理は関数を 1 つ渡すだけで、読込中・成功・失敗・空・二重送信・中断が付いてきます。\r\n            上のスイッチでトンマナ（見た目の系統）を切り替えると、\r\n            色・角丸・影・書体・余白の広さまで一斉に変わります。": "Nine spacing steps by default, so layout never stalls you. The nine are not a limit — values outside them work as written. For async work you hand over one function and get loading, success, failure, empty, double-submit, and abort with it. Flip the switch above and the whole look — color, radius, shadow, typeface, and the size of the spacing — changes together.",
  "余白は迷わせない。": "Spacing you do not have to decide.",
  "使う言語（複数選択）": "Languages (choose several)",
  "使えない": "Disabled",
  "例": "Example",
  "保存しました": "Saved",
  "保存する": "Save",
  "保留中:": "Pending:",
  "値": "Value",
  "停止": "Stop",
  "停止中": "Locked",
  "優先度": "Priority",
  "元に戻す": "Undo",
  "元に戻せません。": "This cannot be undone.",
  "入れ子も揃います": "Nesting lines up too",
  "入力/選択": "Input & select",
  "入力すると絞り込みます（応答に 350ms かかる想定にしてあります）": "Type to filter (responses are made to take 350ms on purpose)",
  "入力のたびに投げないよう 250ms の debounce を入れ、\r\n          打ち直すと": "A 250ms debounce keeps it from firing on every keystroke, and typing again",
  "入力内容を確認してください": "Please check what you entered",
  "入力欄の文字サイズ": "Input font size",
  "入力補完に出るのはこの 9 つだけなので、迷わずに済みます。\r\n          ただし壁ではありません。": "Autocomplete offers only these nine, so there is nothing to weigh up. They are not a wall, though.",
  "再取得（保留中は消えません）": "Refetch (pending items stay)",
  "処理が完了しました": "Finished",
  "処理中…": "Working…",
  "利用規約・法務": "Terms & legal",
  "削除": "Delete",
  "削除しました": "Deleted",
  "削除する": "Delete",
  "削除・決済・送信だと、利用者が「やめた」と思った後に起きます。\r\n          下の guard は": "For a delete, a payment, or a send, that happens after the user believes they backed out. The guard below",
  "削除中": "Deleting",
  "前のリクエストは自動で中断": "The previous request is aborted automatically",
  "効きます\r\n          （ドラッグして落とす経路は素通りしがちです）。": "applies (the drag-and-drop path is the one that usually slips through).",
  "包まない（下の文章がずれます）": "Unwrapped (the text below shifts)",
  "千葉 みなと": "Minato Chiba",
  "単体で使う（複数開けます）": "On its own (several can be open)",
  "取り消しました": "Cancelled",
  "取り消します。\r\n          「配列を控えて戻す」実装だと、同時に走った他の操作まで巻き戻ります。\r\n          保留中の行は薄く表示されます。": "are rolled back. An implementation that snapshots the array and restores it would also undo whatever else was running at the same time. Pending rows are shown faded.",
  "取得・スケルトン・空状態・失敗と再試行を 1 コンポーネントに閉じ込めています。下のボタンで各状態を確認できます。": "Fetching, skeleton, empty, failure, and retry are all sealed into one component. The buttons below show each state.",
  "右から出す": "From the right",
  "受付中": "Ready",
  "同じ画面操作の重なりだけを止めます。通信の状態、成功表示、retry、AbortSignal は持ちません。それらが必要なら useAction を選びます。いつ再び許可するかは、操作の意味を知る利用側が release() で決めます。": "Stops only overlapping attempts at the same UI operation. It has no request state, success UI, retry, or AbortSignal; choose useAction when you need those. The caller, which knows what the operation means, decides when to allow it again with release().",
  "同期する": "Sync",
  "名前で検索": "Search by name",
  "呼ばれた回数:": "Times called:",
  "問い合わせ": "Contact",
  "問い合わせフォームを API に接続": "Connect the contact form to an API",
  "在庫の取得に失敗しました": "Could not load stock levels",
  "壊しにくる中身を入れてみる": "Try content that goes out of its way to break things",
  "外側の枠をそれより手前に置いてください。": "put the outer frame in front of it.",
  "失敗": "Failure",
  "失敗する": "Fail",
  "完了": "Done",
  "実寸 1600px の画像": "An image that is really 1600px wide",
  "実行する": "Run",
  "実行するとここに結果が出ます": "Run it and the result appears here",
  "実際に送信された値": "What was actually submitted",
  "導入事例": "Case studies",
  "小さいスマホ": "Small phone",
  "属性でブラウザに任せています。": "attribute leaves it to the browser.",
  "履歴": "History",
  "山田 太郎": "Taro Yamada",
  "崩れがあれば 1。CI に載せられます": "Exits 1 when something is broken, so it drops into CI",
  "崩れていないことを数値で確かめる": "Prove nothing is broken, with numbers",
  "幅 {0}px のプレビュー": "Preview at {0}px",
  "幅は持たせていません。": "It carries no width of its own.",
  "幅を変えても崩れません": "Nothing breaks as the width changes",
  "引用。左に線が入り、色が一段落ちます。": "A quotation. A rule appears on the left and the color steps down.",
  "成功する": "Succeed",
  "戻す": "Reset",
  "技術": "Engineering",
  "折り返さない長いラベル 1": "A long label that will not wrap 1",
  "折り返さない長いラベル 2": "A long label that will not wrap 2",
  "折り返さない長いラベル 3": "A long label that will not wrap 3",
  "折り返さない長いラベル 4": "A long label that will not wrap 4",
  "折り返せない長い URL": "A long URL with nowhere to break",
  "押すと何かが起きるのか、どこかへ行くのか": "whether pressing it does something or goes somewhere",
  "担当": "Owner",
  "担当者": "Assignee",
  "親から Bob に変更": "Change to Bob from the parent",
  "親からクリア": "Clear from the parent",
  "控えめに実行": "Run quietly",
  "握られなかった失敗:": "Failures nobody caught:",
  "操作": "Actions",
  "操作を受け付けました": "Accepted",
  "支払い方法は？": "Which payment methods do you take?",
  "文字列だけ渡す": "Pass a plain string",
  "料金": "Pricing",
  "既定では隠すだけなので、上の入力は残っています。": "By default it only hides, so what you typed above is still there.",
  "日付": "Date",
  "更新中": "Updating",
  "書き出しました": "Exported",
  "書き出す": "Export",
  "期限": "Due",
  "本当に削除しますか？": "Delete this for real?",
  "次へ進む": "Continue",
  "本文/画像": "Text & images",
  "本文です。行の長さは": "Body text. The line length is set by",
  "本文へ": "Skip to content",
  "フォームをリセット": "Reset form",
  "案件": "Project",
  "案件 A": "Project A",
  "案件 B": "Project B",
  "案件 C": "Project C",
  "案件 D": "Project D",
  "案件 E": "Project E",
  "案件 F": "Project F",
  "案件 G": "Project G",
  "案件 H": "Project H",
  "案件 {0}": "Project {0}",
  "案件の一覧": "Project list",
  "概要": "Overview",
  "標準的なスマホ": "Typical phone",
  "横の動きだけ": "Horizontal movement only",
  "横スクロールの発生": "Horizontal overflow",
  "横並び": "Side by side",
  "橋本 そら": "Sora Hashimoto",
  "機械学習": "Machine learning",
  "機能一覧": "Features",
  "段組は狭い画面で自動的に縦へ畳み、タイルは列数が変わり、\r\n                タグは折り返します。長い URL も折れます。\r\n                https://example.com/very/long/path/that/never/breaks/anywhere": "Columns fold to a stack on a narrow screen, tiles change their column count, and tags wrap. Long URLs break too. https://example.com/very/long/path/that/never/breaks/anywhere",
  "段階に無い値も書けます:": "Off-scale values work too:",
  "比率を変えた例": "With a different ratio",
  "無料": "Free",
  "状態": "State",
  "状態は書かせない。": "State you do not have to write.",
  "状態管理": "State management",
  "狭い画面では縦に畳みます。": "It folds to a stack on narrow screens.",
  "狭い画面のメニューは": "The narrow-screen menu is",
  "画像か PDF、1 ファイル 2 MB まで": "Images or PDFs, up to 2 MB each",
  "画像は読み込みが終わるまで大きさが分かりません。何もしないと、\r\n          読み込んだ瞬間に": "An image has no known size until it has loaded. Do nothing and, the moment it arrives,",
  "画像を読み込む": "Load the image",
  "画面から消しました": "Removed from the screen",
  "画面から消す": "Remove from the screen",
  "画面が狭くなると自動で折り返すので、はみ出しません。ウィンドウ幅を変えてみてください。": "It wraps by itself as the screen narrows, so nothing overflows. Try changing the window width.",
  "画面の広い端末で見るためのものです。": "It is meant for looking at on a wide screen.",
  "画面幅より大きい min-width / flex-shrink:0": "A min-width wider than the viewport, or flex-shrink:0",
  "畳まない": "Never fold",
  "畳んでいる間は": "While it is folded,",
  "登録が完了しました": "You are signed up",
  "矢印キーで移動できるのが本体": "Arrow-key movement is the real point",
  "破棄しました": "Discarded",
  "確認してから実行": "Confirm, then run",
  "確認つき": "With confirmation",
  "確認メールを送ります": "We will send a confirmation email",
  "確認中…": "Confirming…",
  "確認中にやめる": "Cancel while confirming",
  "空": "Empty",
  "端末プレビュー": "Device preview",
  "端末幅": "Screen width",
  "端末幅を確かめる": "Check the screen width",
  "箇条書き": "A bulleted list",
  "終了コード": "Exit code",
  "縦積み（width は効きません）": "Stacked (width has no effect)",
  "縮まない固定幅": "A fixed width that will not shrink",
  "縮むのはリンクの列ではなく説明文です。": "What shrinks is the description, not the row of links.",
  "自分": "Me",
  "自前で処理しました": "Handled it myself",
  "藤本 かえで": "Kaede Fujimoto",
  "行選択": "Row selection",
  "行間": "Line height",
  "行間は 1.85。和文は詰まって見えやすいので広めにしています": "Line height is 1.85 — Japanese text looks cramped easily, so it is set wide",
  "表のように、これ以上縮めると読めなくなる中身があります。\r\n          無理に折り返すのではなく、その部分だけ横スクロールさせるのが正解です。\r\n          端が切れていることを示す影が出て、キーボードでも到達できます。\r\n          ホイールは": "Some content — a table, say — becomes unreadable if you shrink it further. Rather than forcing a wrap, the right answer is to scroll that part horizontally. A shadow marks the cut-off edge, and it is reachable by keyboard. For the wheel,",
  "製品": "Products",
  "複数選べます（パソコンでは Ctrl / ⌘ を押しながらクリック）": "You can pick several (on a computer, hold Ctrl / ⌘ and click)",
  "複製しました": "Duplicated",
  "複製する": "Duplicate",
  "要素数が半端でも崩れません。列数は画面幅ごとに指定できます。列数を決めず、幅で自動的に折り返させることもできます。": "It does not break on an awkward number of items. The column count can be set per screen width, or left undecided so the width wraps them automatically.",
  "見た目は同じでも別部品にしています。": "They look the same but are separate components.",
  "見ているのは名前とブラウザの推測だけなので、\r\n          受け取るサーバ側で必ず確かめてください。": "All it looks at is the name and the browser's guess, so always verify on the receiving server.",
  "見出しの上余白": "Space above a heading",
  "見出しの例": "A sample heading",
  "見本です。押しても実際には何も消えません。": "This is a sample. Pressing it deletes nothing.",
  "見本です。押しても実際には何も送信されません。": "This is a sample. Pressing it sends nothing.",
  "見本です。選んだファイルはどこにも送られません（進捗は偽物です）。": "Sample only. Files go nowhere; the progress is fake.",
  "規約に同意する": "I agree to the terms",
  "詳細": "Details",
  "説明文は何行になっても読めますが、リンクの列は縦に割れると\r\n          「まとまり」が見えなくなります。列が増えて器に収まらなくなったら、\r\n          説明文を潰さずに次の行へ落とします。": "A description stays readable however many lines it takes, but a column of links stops reading as a group once it splits vertically. When there are too many columns to fit, they drop to the next line rather than squashing the description.",
  "読みやすい行長は": "A readable line length is set by",
  "返品できますか？": "Can I return it?",
  "追加": "Add",
  "追加・削除・更新をサーバーの応答を待たずに反映し、失敗したら": "Adds, removes, and updates land without waiting for the server, and on failure they",
  "追加中": "Adding",
  "送信して中身を見る": "Submit and look at the payload",
  "送信する": "Submit",
  "送信関数を 1 つ渡すだけ。": "Hand it one submit function.",
  "通知の設定": "Notification settings",
  "通知を直接出す": "Show a notification directly",
  "通った回数:": "Accepted attempts:",
  "進行中": "In progress",
  "詳細を開く": "Open details",
  "適用": "Apply",
  "選んだときも落としたときも": "Whether you pick them or drop them",
  "選択してください": "Please choose one",
  "選択は": "The selection is",
  "選択中:": "Selected:",
  "部品": "Components",
  "部品の仕様ではありません。": "This is not how the component behaves.",
  "部品の仕様ではありません。失敗したときの戻り方を見るための細工です。": "This is not how the component behaves — it is rigged so you can watch how it recovers from a failure.",
  "重い処理を実行": "Run something heavy",
  "金額": "Amount",
  "長い英単語": "A long word with no spaces",
  "長すぎる本文は読みにくい": "Body text that runs too long is hard to read",
  "閉じる": "Close",
  "開発": "Development",
  "開発者向け": "For developers",
  "隠しても、端の影とキーボード操作は残ります": "Hidden or not, the edge shadow and keyboard access stay",
  "静的なページは Astro、動く部分だけ React。この部品で組んだサイトの見本です。": "Static pages in Astro, React only where things move. A sample site built from these components.",
  "項目": "Item",
  "領収書は出ますか？": "Can I get a receipt?",
  "高": "High",
  "（レイアウトシフト）。比率さえ決めておけば、画像がまだ来ていなくても\r\n          高さが確定します。画像そのものの最適化はしません。Astro\r\n          の": "(layout shift). Fix the ratio and the height is settled before the image arrives. Optimizing the image itself is not this component's job — that is Astro's",
  "）を書いても、はみ出さずに折り返します。": ") and it still wraps instead of overflowing.",
  "Switcher — 中身が成立する幅で切り替える": "Switcher — switch when the content no longer fits",
  "viewport の breakpoint ではなく、置かれた器の中で各項目に必要な幅が取れるかを見ます。狭ければ JavaScript 無しで 1 列になります。": "It checks whether each item gets the width it needs inside its actual container, not a viewport breakpoint. When space is tight it becomes one column without JavaScript.",
  "<Switcher minItemWidth=\"18rem\" space=\"lg\">\n  <Profile />\n  <Settings />\n</Switcher>": "<Switcher minItemWidth=\"18rem\" space=\"lg\">\n  <Profile />\n  <Settings />\n</Switcher>",
  "プロフィール": "Profile",
  "長い内容でも、隣を縮み潰さずに必要な幅で縦へ切り替わります。": "Even with long content, it switches to a vertical layout at the required width instead of crushing its neighbor.",
  "表示名": "Display name",
  "なす スタック": "Nasu Stack",
  "設定の章": "Settings sections",
  "アカウント": "Account",
  "通知": "Notifications",
  "セキュリティ": "Security",
  "SidebarLayout — side と本文が入るときだけ 2 列": "SidebarLayout — two columns only when side and content fit",
  "開閉やnavigation状態を持つ Sidebar ではなく、配置だけを持つため SidebarLayout です。side と本文の最小幅が同時に取れなければ 1 列になり、DOM 順と見た目の順は一致したままです。": "It is SidebarLayout, not an interactive Sidebar, because it owns layout only. If the minimum widths for the side and content do not both fit, it becomes one column while DOM order and visual order remain aligned.",
  "<SidebarLayout\n  side={<Nav />}\n  sideWidth=\"18rem\"\n  contentMinWidth=\"30rem\"\n  sidePosition=\"start\"\n>\n  <Article />\n</SidebarLayout>": "<SidebarLayout\n  side={<Nav />}\n  sideWidth=\"18rem\"\n  contentMinWidth=\"30rem\"\n  sidePosition=\"start\"\n>\n  <Article />\n</SidebarLayout>",
  "アカウント設定": "Account settings",
  "本文は残りを埋めます。器が足りないときだけ、side と本文がそれぞれ全幅になります。": "The content fills the remaining space. Only when the container is too narrow do the side and content each take the full width.",
  "件名は 3 文字以上で入力してください": "Enter at least 3 characters for the title",
  "入力部品と validation contract": "Input components and the validation contract",
  "AsyncForm は FormData を畳んで validate に渡します。failure なら field error を表示し、success なら変換済み data だけを action へ渡します。ブラウザ側の検査は早い feedback であり、server 側の正規の判定は置き換えません。": "AsyncForm folds FormData and passes it to validate. A failure becomes field errors; on success, only transformed data goes to the action. Browser validation is early feedback and never replaces authoritative server validation.",
  "const validate: Validator<Profile, FormValues> = (values) => {\n  if (!values.plan) {\n    return { ok: false, fields: { plan: [\"選んでください\"] } };\n  }\n  return { ok: true, data: {\n    title: String(values.title).trim(),\n    plan: String(values.plan),\n  } };\n};\n\n<AsyncForm validate={validate} action={(profile) => api.save(profile)}>\n  …\n</AsyncForm>": "const validate: Validator<Profile, FormValues> = (values) => {\n  if (!values.plan) {\n    return { ok: false, fields: { plan: [\"Choose one\"] } };\n  }\n  return { ok: true, data: {\n    title: String(values.title).trim(),\n    plan: String(values.plan),\n  } };\n};\n\n<AsyncForm validate={validate} action={(profile) => api.save(profile)}>\n  …\n</AsyncForm>",
  "QA チームは現在選べません": "The QA team is not available right now",
  "メールアドレスを入力してください": "Enter an email address",
  "メンバーを 1 人以上追加してください": "Add at least one member",
  "繰り返し入力の stable key・nested name・min/max・focus をまとめます。追加後は新しい行、削除後は隣の行へ移り、残った入力値は index が変わっても消えません。並べ替え・永続 ID・正規の validation はアプリと server の担当です。": "It handles stable keys, nested names, min/max limits, and focus for repeated fields. Focus moves into a new row after adding and to a neighboring row after removal, while remaining values survive index changes. Reordering, persistent IDs, and authoritative validation stay with the app and server.",
  "<FieldArray\n  name=\"members\" label=\"Members\" min={1} max={3}\n  defaultItems={[{ email: \"\" }]}\n  createItem={() => ({ email: \"\" })}\n  addLabel=\"Add member\"\n  removeLabel={({ index }) => `Remove member ${index + 1}`}\n  emptyMessage=\"No members yet\"\n>\n  {({ name, index, defaultValue }) => (\n    <Field name={`${name}.email`} label={`Member ${index + 1} email`}\n      defaultValue={defaultValue.email} />\n  )}\n</FieldArray>": "<FieldArray\n  name=\"members\" label=\"Members\" min={1} max={3}\n  defaultItems={[{ email: \"\" }]}\n  createItem={() => ({ email: \"\" })}\n  addLabel=\"Add member\"\n  removeLabel={({ index }) => `Remove member ${index + 1}`}\n  emptyMessage=\"No members yet\"\n>\n  {({ name, index, defaultValue }) => (\n    <Field name={`${name}.email`} label={`Member ${index + 1} email`}\n      defaultValue={defaultValue.email} />\n  )}\n</FieldArray>",
  "メンバーを保存": "Save members",
  "メンバーを保存しました": "Members saved",
  "メンバー": "Members",
  "1〜3 人。行を消しても、残った入力値は保たれます。": "One to three people. Other values stay after removal.",
  "メンバーを追加": "Add member",
  "メンバー {0} を削除": "Remove member {0}",
  "メンバーはまだいません": "No members yet",
  "メンバー {0} のメール": "Member {0} email",
  "保存したメンバー": "Saved members",
  "任意の補足": "Optional note",
  "最低行数を 2 にする": "Require two notes",
  "補足をリセット": "Reset notes",
  "現在の最低行数: {0}": "Current minimum: {0}",
  "補足を追加": "Add a note",
  "補足を削除": "Remove the note",
  "補足はまだありません。必要なら追加できます。": "No note yet. Add one if you need it.",
  "補足": "Note",
  "Reactのrender failureだけをこの範囲へ閉じ込めます。失敗するとfallbackへfocusし、siblingはそのまま残ります。event handlerやasync errorはuseAction / AsyncBoundaryの責任です。": "It contains only React render failures within this area. Focus moves to the fallback while siblings remain usable. Event-handler and async errors belong to useAction / AsyncBoundary.",
  "<ErrorBoundary\n  title=\"この部分を表示できませんでした\"\n  retryLabel=\"もう一度試す\"\n  onError={reportRenderFailure}\n>\n  <Dashboard />\n</ErrorBoundary>": "<ErrorBoundary\n  title=\"This area could not be displayed\"\n  retryLabel=\"Try again\"\n  onError={reportRenderFailure}\n>\n  <Dashboard />\n</ErrorBoundary>",
  "この見本を表示できませんでした": "This example could not be displayed",
  "ページのほかの部分はそのまま利用できます。": "The rest of the page is still available.",
  "もう一度試す": "Try again",
  "境界の外側は利用できます。捕捉回数:": "Outside the boundary remains usable. Caught:",
  "この範囲だけを壊す": "Break only this area",
  "下書きの保存に失敗しました": "The draft could not be saved",
  "保存中…": "Saving…",
  "保存できませんでした": "Could not save",
  "未保存の変更あり": "Unsaved changes",
  "保存済み": "Saved",
  "まだ変更はありません": "No changes yet",
  "高速入力をdebounceし、保存中に増えた変更は途中の値を捨てて最新値だけを次へ送ります。cancelはUIへ古い結果を戻さないだけで、serverのwriteを取り消す保証ではありません。": "It debounces rapid input and, when changes arrive during a save, discards intermediate values so only the latest is sent next. Cancel keeps stale results out of the UI; it does not guarantee that a server write was undone.",
  "const draft = useAutosave(saveArticle, { delay: 800 });\n\n<textarea\n  onChange={(event) => draft.schedule(event.currentTarget.value)}\n  onBlur={draft.flush}\n/>\n<output aria-live=\"polite\">{draft.status}</output>": "const draft = useAutosave(saveArticle, { delay: 800 });\n\n<textarea\n  onChange={(event) => draft.schedule(event.currentTarget.value)}\n  onBlur={draft.flush}\n/>\n<output aria-live=\"polite\">{draft.status}</output>",
  "下書き": "Draft",
  "今すぐ保存": "Save now",
  "未保存を破棄": "Discard unsaved changes",
  "再試行": "Retry",
  "triggerのそばへ補助的な内容を出し、外側pointer・Esc・focus復帰・viewport端の補正を引き受けます。": "It places supporting content beside its trigger and handles outside pointers, Escape, focus return, and viewport-edge correction.",
  "中身のroleや選択状態は決めません。": "It does not decide the content role or selection state.",
  "命令の一覧はDropdownMenu、modalな内容はDialogを使います。portalを使わないので、Tab順序はDOMのままです。": "Use DropdownMenu for command lists and Dialog for modal content. It does not use a portal, so Tab order follows the DOM.",
  "<Popover trigger=\"詳細\" placement=\"auto\" align=\"end\">\n  <p>最終更新は5分前です。</p>\n</Popover>\n\n// 自分のButtonを使うとき\n<Popover trigger={(props) => <Button {...props}>詳細</Button>}>…</Popover>": "<Popover trigger=\"Details\" placement=\"auto\" align=\"end\">\n  <p>Last updated five minutes ago.</p>\n</Popover>\n\n// To use your own Button\n<Popover trigger={(props) => <Button {...props}>Details</Button>}>…</Popover>",
  "詳細を表示": "Show details",
  "これは補足情報です。狭い画面の右端や最下部でも、読める範囲をviewport内へ残します。": "This is supporting information. Even at the right or bottom edge of a narrow screen, the readable area remains inside the viewport.",
  "内容から閉じる": "Close from content",
  "制御されたPopover": "Controlled Popover",
  "openとonOpenChangeを親が所有しています。": "The parent owns open and onOpenChange.",
  "親から開閉": "Toggle from parent",
  "外側の操作": "Outside action",
  "記事のページ": "Article pages",
  "前のページ": "Previous page",
  "次のページ": "Next page",
  "ページ {0}": "Page {0}",
  "移動先を本物のlinkとして残したまま、現在page・前後・巨大なpage数のellipsisを扱います。": "It keeps every destination as a real link while handling the current page, previous and next links, and ellipses for very large page counts.",
  "totalの取得とURLの意味はapplicationの責任です。": "Fetching the total and defining URL meaning remain application responsibilities.",
  "client routerはmodifierのない通常clickだけを横取りし、新しいtabで開く経路を残します。": "A client router intercepts only ordinary unmodified clicks, preserving the path to open a link in a new tab.",
  "<Paginator\n  currentPage={page}\n  totalPages={1000}\n  getHref={(next) => `/articles?page=${next}`}\n/>\n\n// client routerを使う場合もhrefは残し、通常clickだけpreventDefaultします": "<Paginator\n  currentPage={page}\n  totalPages={1000}\n  getHref={(next) => `/articles?page=${next}`}\n/>\n\n// Keep href with a client router too; preventDefault only for ordinary clicks",
  "先頭へ": "First",
  "中間へ": "Middle",
  "末尾へ": "Last",
  "現在: ページ {0}": "Current: page {0}",
  "コピー中…": "Copying…",
  "コピーしました": "Copied",
  "もう一度コピー": "Try copying again",
  "コピーしています": "Copying",
  "クリップボードにコピーしました": "Copied to clipboard",
  "コピーできませんでした": "Could not copy",
  "Clipboard APIの成功・失敗・fallback・resetだけを扱います。コピーしてよい情報かは判断しません。秘密情報や個人情報を渡してよいかはapplication側で決めます。": "It handles only Clipboard API success, failure, fallback, and reset. It does not decide whether information may be copied. The application decides whether secrets or personal data may be passed in.",
  "<CopyButton text={shareUrl}>リンクをコピー</CopyButton>\n\n// 独自の見た目や処理なら1段下へ\nconst copy = useCopy({ resetAfter: 2000 });\nawait copy.copy(text);": "<CopyButton text={shareUrl}>Copy link</CopyButton>\n\n// Drop down one layer for custom appearance or behavior\nconst copy = useCopy({ resetAfter: 2000 });\nawait copy.copy(text);",
  "コピーする文字": "Text to copy",
  "リンクをコピー": "Copy link",
  "検索に失敗しました": "Search failed",
  "再試行で取得できた結果": "Result loaded after retry",
  "古い検索結果": "Old search result",
  "新しい検索結果": "Current search result",
  "責任境界": "Responsibility boundaries",
  "認証・認可・rate limitはserverの責任として残します。": "Authentication, authorization, and rate limits remain server responsibilities.",
  "長い結果でも狭い画面を押し広げません。": "Long results do not push a narrow viewport wider.",
  "入力が止まってから検索し、新しい検索語を待つ間は古い結果を隠します。前のrequestは中断し、失敗・再試行・空状態も同じ配線で扱います。検索の意味、権限、rate limit、順位付けはappとserverの責任です。": "It searches after input settles and hides old results while a new query waits. The same wiring aborts the previous request and covers failure, retry, and empty states. Query meaning, permissions, rate limits, and ranking belong to the app and server.",
  "<SearchListRecipe\n  search={(query, ctx) => searchArticles(query, ctx)}\n  messages={{ label: \"記事を検索\" }}\n/>": "<SearchListRecipe\n  search={(query, ctx) => searchArticles(query, ctx)}\n  messages={{ label: \"Search articles\" }}\n/>",
  "サイト内検索": "Search this site",
  "名前や説明で検索": "Search names and descriptions",
  "{0}文字以上入力すると検索します。": "Enter at least {0} characters to search.",
  "検索中…": "Searching…",
  "一致する結果はありません。": "No matching results.",
  "検索を再試行": "Try search again",
  "検索結果 {0} 件": "{0} search results",
  "cursor一覧の最初の記事": "The first cursor-list article",
  "最初のpageは自動で取得します。": "The first page loads automatically.",
  "長い結果も狭い画面を押し広げません。": "Long results do not widen a narrow screen.",
  "次のpageを取得できませんでした": "The next page could not be loaded",
  "追加してはいけないloop結果": "Loop result that must not be appended",
  "同じcursorへ戻るためfail closedになります。": "It fails closed because the cursor returns to one already loaded.",
  "追加された記事A": "Appended article A",
  "buttonを押した後もfocus位置を保ちます。": "Focus remains in place after activating the button.",
  "追加された記事B": "Appended article B",
  "同じcursorを連打してもrequestは1回です。": "Repeated activation for the same cursor still makes one request.",
  "最後の記事": "The final article",
  "末尾ではbuttonをend stateへ置き換えます。": "At the end, the button becomes an end state.",
  "通常のcursor list": "Normal cursor list",
  "次page失敗": "Next page failure",
  "空のcursor list": "Empty cursor list",
  "0件だが次があるpage": "Empty page with a next cursor",
  "cursor loop": "Cursor loop",
  "不正なcursor page": "Invalid cursor page",
  "自動無限scrollではなく明示的なbuttonを既定にし、cursor requestの連打・stale response・失敗したpageのretry・末尾・cursor loopを扱います。itemの重複、並び順、認可、cursor発行はappとserverの責任です。": "It defaults to an explicit button instead of automatic infinite scroll and handles repeated cursor requests, stale responses, retrying the failed page, the end state, and cursor loops. Item duplication, ordering, authorization, and cursor issuance belong to the app and server.",
  "<LoadMoreList\n  loader={(cursor, ctx) => getArticles(cursor, ctx)}\n  renderItem={(article) => <a href={article.href}>{article.title}</a>}\n  getKey={(article) => article.id}\n/>": "<LoadMoreList\n  loader={(cursor, ctx) => getArticles(cursor, ctx)}\n  renderItem={(article) => <a href={article.href}>{article.title}</a>}\n  getKey={(article) => article.id}\n/>",
  "記事": "Articles",
  "最初のpageを読込中…": "Loading the first page…",
  "さらに読み込む": "Load more",
  "次のpageを読込中…": "Loading the next page…",
  "このpageを再試行": "Try this page again",
  "記事はまだありません。": "No articles yet.",
  "すべての記事を読み込みました。": "All articles have been loaded.",
  "記事 {0} 件": "{0} articles",
  "serverが既に取得したcursorを返しました。": "The server returned a cursor that was already loaded.",
  "serverが不正なcursor pageを返しました。": "The server returned an invalid cursor page.",
};
